[alias]
bench-dev = "build --no-default-features --features board-f411-nucleo,bench --target thumbv7em-none-eabihf"
bench-release = "build --release --no-default-features --features board-f411-nucleo,bench --target thumbv7em-none-eabihf"
bench-release-build = "build --release --no-default-features --features board-f411-nucleo,bench --target thumbv7em-none-eabihf"

[target.thumbv7em-none-eabihf]
rustflags = [
  "-C", "link-arg=-Tlink.x",
]

[target.thumbv7m-none-eabi]
rustflags = [
  "-C", "link-arg=-Tlink.x",
]
